### ISSUE TITLE
KILL script type is not recognized.

### ISSUE THREAD

**Issue by Doruk-Aksoy** [wormt/bcc#10]
As per this ticket: http://zandronum.com/tracker/view.php?id=3089 -- it appears Zandronum supports this script type but BCC doesn't.

EDIT: I just realized there's a more up-to-date branch named 'bcs'. That one supports this.

**Comment by positively-charged** [comment]
KILL scripts are included in the latest release: [0.8.0](https://github.com/wormt/bcc/releases/tag/0.8.0)

Regarding new features, the `bcs` branch is up to date with the [ACC](https://github.com/rheit/acc/) repository. I should merge the `bcs` branch with the `master` branch. I kept them separate because they're incompatible with each other in many ways. I thought I'd keep it up for some time for those who are interested in the old branch.
