### ISSUE TITLE
Non-void functions never tested for missing return value

### ISSUE THREAD

**Issue by caiosm1005** [wormt/bcc#5]
In stmt.c `test_return` there is a condition that is never met.

```
if ( stmt->return_value ) {
   // ...
}
else {
   if ( target->func->return_type ) {
      t_diag( task, DIAG_POS_ERR, &stmt->pos,
         "missing return value in function `%s`", str.value );
      t_bail( task );
   }
}
```

Since this test occurs only when the parser finds a return statement, a non-void function without a return statement will be overlooked.

In the current state, the code below compiles without errors:

```
function str test()
{
    // No return
}
```

**Comment by wormt** [comment]
I did this on purpose. The reason is that checking every possible path of execution for a `return` statement is complicated. The `goto` statement contributes to the complexity of the task. At this time, I haven't developed a good way to solve this.

This behavior is undefined, but the compiler handles it somewhat. At the end of a function, the compiler generates code that returns a zero. So even though a `return` statement might not be encountered, it will still work, although possibly erroneously.

**Comment by positively-charged** [comment]
This is now resolved for the most part. You can still bypass the check by using a `goto` statement if you want.

**Comment by caiosm1005** [comment]
@wormt nice to see you're still working on this. I forked it a while ago for a project I was making for Zandronum, but I unfortunately found myself with no spare time to continue.

One of my goals when I forked `bcc` was to create some sort of string concatenation mechanism using the `+` operator, which basically would do some clever tricks using [StrParam](http://zdoom.org/wiki/StrParam) under the hood.

**Comment by positively-charged** [comment]
Hey, @caiosm1005. Nice to see you around.

I worked my ass off on **bcc** this year. Added a bunch of features. One of them is a type system. It supports string concatenation via the `+` operator. A `fixed` type is also supported. More information can be found in the [Strong Types](https://github.com/wormt/bcc/blob/bcs/doc/details.md#strong-types) section of the documentation.
